### ISSUE TITLE
Documentation - Add Method Invocation Example

### ISSUE THREAD

**Issue by XavierGeerinck** [dapr/js-sdk#105]
We strive to have easy to use examples that help everyone. For this issue we are looking for an example that describes how to use Method Invocation for HTTP and gRPC.

**Comment by dolencd** [comment]
I can do this 🙂 

One thing to discuss though:
Currently the examples are fundamentally split between HTTP and gRPC examples. Should I do this one this way as well? (So there would be 2 nearly identical examples, one with HTTP and one with gRPC)
I think that since the API is the same, it would make more sense to have a single example in (for example) `examples/invocation` that would be easy to switch from one protocol to the other (comment/uncomment a few lines, run `npm run start:dapr-grpc` or `npm run start:dapr-http`)
