### ISSUE TITLE
Add support for promises

### ISSUE THREAD

**Issue by marcus-sa** [dapr/js-sdk#12]
Promise support is a must have and is definitely preferred over callbacks.

**Comment by brendandburns** [comment]
@marcus-sa This code is generated by the gRPC code generator. Please see the issue here:

https://github.com/grpc/grpc-node/issues/54

Discussing why they still use callbacks.

I'm going to investigate `grpc-helper` and see if we can use that.

Failing at that, hand-written code to help with this is also ok...

**Comment by thebillkidy** [comment]
> @marcus-sa This code is generated by the gRPC code generator. Please see the issue here:
> 
> [grpc/grpc-node#54](https://github.com/grpc/grpc-node/issues/54)
> 
> Discussing why they still use callbacks.
> 
> I'm going to investigate `grpc-helper` and see if we can use that.
> 
> Failing at that, hand-written code to help with this is also ok...

Was looking at the same thing for promises, apparently there is a bug that has to get resolved first (PR is open at: https://github.com/xizhibei/grpc-helper/pull/9/files#diff-3cafb86a5b0a9d0916a7fed543a1fb53)

**Comment by XavierGeerinck** [comment]
Promises have been added in the entire library now, so closing this.
