### ISSUE TITLE
JS-SDK client uses environment variables to initialize

### ISSUE THREAD

**Issue by paulyuk** [dapr/js-sdk#178]
## Describe the proposal
Currently the Dapr sidecar is setting environment variables on your behalf like DAPR_HOST and DAPR_PORT.  The proposal is to have a default constructor for the DaprClient() that sets the internal host, port, and API version using these environment variables.  

This has the benefits of:
- consistency with other SDKs like Python and .NET: [example](https://github.com/dapr/python-sdk/blob/master/dapr/clients/http/client.py)
- Less user code to get the best practice

Upon completion the user should be able to successfully write this code with parameterless ctor to successfully connect to sidecar and call APIs:
```
const client = new DaprClient();
await client.pubsub.publish("order_pub_sub", "orders", {orderId: 100});
```

**Comment by XavierGeerinck** [comment]
This should be possible as https://docs.dapr.io/reference/environment/ expoes `DAPR_HTTP_PORT`, `DAPR_GRPC_PORT` and `APP_PORT`. Would need to check if when running `dapr run` this is set as well.

**Comment by shubham1172** [comment]
I see `DAPR_API_VERSION` in python-sdk [here](https://github.com/dapr/python-sdk/blob/e167ec089cb8a614f675ee799b4aa978d1422852/dapr/conf/global_settings.py#L25), but this is not present in any other SDK or CLI/Runtime repositories. It's not documented here too - https://docs.dapr.io/reference/environment/

This does not look like a supported feature. @paulyuk, thoughts?

Also, since we are refactoring `DaprClient`, we can refactor `DaprServer` also under the same work-item.
