### ISSUE TITLE
Actors in js

### ISSUE THREAD

**Issue by VarunPeddina** [dapr/js-sdk#18]
Just want to know if this feature (being able to write actors in javascript) along with pub sub dapr/dapr#501 is there in the roadmap.

**Comment by amanbha** [comment]
@VarunPeddina Once the feature described in dapr/dapr#501 is implemented in Dapr runtime, it will available across all the languages.

**Comment by VarunPeddina** [comment]
@amanbha Thank you. Saw here dapr/dapr#781 that actor creation is only available via dotnet sdk. Any chance that this might be implemented in the js-sdk as well

**Comment by amanbha** [comment]
@VarunPeddina We are adding actor capabilities to other languages as well. After C#, we are adding it for Java, its just a matter of priority and customer requirements.
For Javascript actor sdk, if you would like to contribute, it would be great and I can work with you to get that in.

To give brief overview of how actors are implemented and why actor SDK is needed:

Dapr runtime has a virtual actor model(similar to Service Fabric reliable actors and Orleans) in it, the following core functionalities of actor runtime are in Dapr Runtime:
	- Actor Activation.
	- Actor deactivation.
	- Ensuring Actor calls follows a Turn based concurrency so that calls to actor are single threaded.
	- Firing Reminder/Timers.
	- State Management for Actor.
 
Since all these functionalities are provided by Dapr runtime, user code written in any language can leverage the Actor functionalities.
 
Now Dapr runtime calls into user code when it decides to do following:
	- On startup gets a list of supported Actor types by the user service code.
	- Activate/Deactivate.
	- Invoke a actor method.
	- Fire timer/reminder for an actor. 
 
User code calls into Dapr to do following:
	- Perform state changes for Actor.
	- Register Timer, reminders.
 
The SDK provides a neat abstraction of all the Dapr <->UserCode interactions for Actors, so that users don’t have to worry about any of the following:
	- Implementing the routes for Dapr calls into user code.
	- Performing state operations against Dapr for Actor.
	- Caching state.
	- Activating/deactivating actors
	- Caching actor objects.
	- Invoking actor methods.
	- Firing timers and reminders.
 
All of the above is handled by the SDK. In addition to these, SDK will also provide helper methods for the clients to make Actor calls. 
Dotnet SDK does all this so that code written by user for Actors is pretty minimal, all user has to do is just provide actor interface, implement the actor methods and register with the web host(AspNetCore in case of C#). Actor SDKs for all the languages will do the same.

**Comment by VarunPeddina** [comment]
Thank you for the opportunity @amanbha . Although I don't have the capability or bandwidth today, an actor subscribing to an event stream and only getting activated/invoked when it has a set of messages to process on any machine in the cluster, with concurrency taken care of, felt much bigger than nodejs streams/workers. Will wait till pubsub with actors is implemented in dontnet sdk

**Comment by igsys** [comment]
Shall actor support be available anytime soon?

**Comment by omidb** [comment]
Is there any plan to extend JS SDK for actors and other capabilities that are available in other languages?

**Comment by XavierGeerinck** [comment]
Actor implementation is available now! Go check it out and let me know if there are issues with it

**Comment by fdauri** [comment]
Hi @XavierGeerinck ,

I'm trying to implement a PoC using Virtual Actor Timer on Dapr with Javascript/Typescript SDK. I started with the example already present in the javascript sdk (http->actor) but I obtain the following error:

src/index.ts:53:24 - error TS2339: Property 'actor' does not exist on type 'DaprClient'.
53   const actor = client.actor.create<DemoActorSayImpl>(DemoActorSayImpl);

It seems that the "actor" reference doesn't exist in the Dapr Client implementation (for pusub and other patterns it works correctly).

Can you help me with some tips?

Thanks!
Francesco

**Comment by XavierGeerinck** [comment]
@fdauri could you make a new issue for this? Also stating the latest NPM version of the `dapr-client` package you are using?

**Comment by shubham1172** [comment]
@fdauri I tried on the latest release and I can use the `actor` property on `DaprClient`. Note that it is only available starting version `2.1.0`. The problem is with the example, it currently points to version `2.0.0`. I will create an issue for it.
