### ISSUE TITLE
Fix actors e2e test

### ISSUE THREAD

**Issue by shubham1172** [dapr/js-sdk#203]
## Expected Behavior

Existing tests should pass.

## Actual Behavior

![image](https://user-images.githubusercontent.com/22132944/155715861-9a114ee1-13df-4f6c-bc68-812f4f65cdbe.png)

```sh
== APP == Test Suites: 1 failed, 1 total
== APP == Tests:       8 failed, 1 passed, 9 total
== APP == Snapshots:   0 total
== APP == Time:        9.229 s
== APP == Ran all test suites matching /test\/e2e\/actors.http.test.ts/i.
```

## Steps to Reproduce the Problem

Run E2E tests

**Comment by shubham1172** [comment]
Able to reproduce it offline.

**Comment by shubham1172** [comment]
The problem is similar to https://github.com/dapr/dapr/issues/3451

https://github.com/dapr/js-sdk/blob/6beae03cdd75f05554758db7b95158645497b5a0/src/implementation/Server/HTTPServer/HTTPServer.ts#L109-L119

Adding a sleep(10s) at line 109 fixes the problem.

**Comment by shubham1172** [comment]
@XavierGeerinck @amulyavarote any thoughts on how to fix this gracefully?

**Comment by XavierGeerinck** [comment]
Aha, this might indeed be due to the Actor Placement tables.

TO fix we can either:
1. Check if the placement tables were updated (not sure how)
2. Wait for Xs (I waited for 4s before if Actors were used)

Personally, I would like to see an `isPlacementTable` updated field or `/actors/healthz` endpoint in `dapr/dapr` since this would fix this as it should

What do you think?

**Comment by shubham1172** [comment]
Yup, I was thinking about the 1st point but it looks like a TODO on the runtime side? We can check-in with the 2nd point as an immediate fix and I can follow up with dapr/dapr for healthz capabilities in actor.

**Comment by XavierGeerinck** [comment]
Agreed
