### ISSUE TITLE
DaprClient's invoker.invoke to have "requiresInitialization" option

### ISSUE THREAD

**Issue by faizahmedfarooqui** [dapr/js-sdk#438]
Hello,

Use-case: I'm running dapr within docker, meaning no local initialisation is needed for dapr.

Looking at the [HTTPClient's execute](https://github.com/dapr/js-sdk/blob/main/src/implementation/Client/HTTPClient/HTTPClient.ts#L145) method, I see that we could pass `requiresInitialization` value as `false` to avoid awaiting SideCar started check.

But the same option isn't being used in our [DaprClient's invoker.invoke](https://github.com/dapr/js-sdk/blob/main/src/implementation/Client/HTTPClient/invoker.ts#L51) method while calling the HTTPClient's execute method.

Let me know if there's any other option to set the same value to avoid checking for initialization that I might have missed out.

Below's how it'd look on making the invoke call from js-sdk.
```js
// Sample Invoke Call
const { DaprClient, HttpMethod } = require("@dapr/dapr");


(async () => {
  var daprClient = new DaprClient("127.0.0.1", "9090");

  const response = await daprClient.invoker.invoke(
    "app-id",
    "method-name",
    HttpMethod.POST,
    { hello: "world" },
    { headers: {}, requiresInitialization: false },
  );

  console.log(response);
})();
```

Thank You :)

**Comment by XavierGeerinck** [comment]
Hi @faizahmedfarooqui ! 

For the JS SDK we have 2 interactions:
* DaprClient: takes care of interacting with the Sidecar (e.g., publish, invoke, ...)
* DaprServer: takes care of the sidecar interactions towards the application (e.g. subscribe, method handling, ...)

We check internally if the communication with the Dapr Sidecar is possible as described in the host and port settings (e.g., your 127.0.0.1 and 9090 in your example). For the DaprClient this happens automatically, for the DaprServer we have the `await server. Start()` method as we need to initialize certain components.

So for your example, you should normally not require any `requiresInitialization` value to be set and the `.invoke` method should work as expected. So a simple `await daprClient.invoker.invoke("app-id", "method-name", HttpMethod.POST, { hello: "world" });` should work

What is the issue you are facing with exactly?

**Comment by faizahmedfarooqui** [comment]
Hello @XavierGeerinck 

Thank you for your response.

Yes, if I expose all my dapr apps (ie. node apps) directly from docker then I might not need to set the same variable to access them from my local machine.

But I've all my dapr apps running in docker using docker-compose and I am using nginx to proxy pass into those different apps.

Let me share you the snapshot of my nginx conf which might help here.

```conf
# Nginx's running on port 9090
location /v1.0/invoke/engine {
      rewrite ^/v1.0/invoke/engine(.*) /v1.0/invoke/engine$1 break;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_cache_bypass $http_upgrade;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://engine:3500;
}
```

So, if I use Postman to hit `http://localhost:9090/v1.0/invoke/engine/method/<some-url>` -- it works as expected but when I use dapr's `Invoker.Invoke` method from SDK - it initiates the same awaiting for sidecar method.

And setting the `requiresInitialization` to `false` manually into the JS SDK works again but this work for my production setting since the changes exist in our node_modules directory.

**Comment by XavierGeerinck** [comment]
Thank you for providing more information. So, behind the scenes, the flow we execute is:

1. User Call (e.g., `.invoke`)
2. HTTP Client goes to generic `execute` method 
3. HTTP Client gets the client with `getClient`
4. Get Client will check if the sidecar communication is up and running in an abstract method named `awaitSidecarStarted` with the interfacing method `HTTPClientSidecar.isStarted`
5. The `HTTPClientSidecar.isStarted` method will execute a Dapr `/metadata` call (https://docs.dapr.io/reference/api/metadata_api/) which we call and require a response back to state that the Sidecar communication is working

The above ensure correct communication for us to baseline and troubleshoot more easily. This is an implementation that supports proxying as it just requires the Dapr sidecar to be available (no matter where it is).

If I look at your nginx configuration, could it be that you are only proxying the `/v1.0/invoke` route? Is there a reason not to proxy the entire `/v1.0` route? Since the `/v1.0/metadata` route is sitting in it as well. This means that you can't access the `/v1.0/metadata` route and initialization will fail. 

Normally everything should work once you proxy that route as well. Let me know if that helps

**Comment by faizahmedfarooqui** [comment]
Hi @XavierGeerinck 

Yes, makes sense.

Actually, in our product's architecture - we are using just the invoke APIs to communicate between our micro-services and hence did not think of exposing traffic on other routes except the invoke.

This really helps. Thanks a lot. :)
